music/urls.py
from django.urls import path
from . import views


app_name = 'music'
urlpatterns = [
    #/music/
    path('', views.IndexView.as_view(), name='index'),

    #/music/21/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),

    path('album/add/', views.AlbumCreate.as_view(), name='album-add'),
    path('album/<int:pk>/', views.AlbumUpdate.as_view(), name='album-update'),
    path('album/<int:pk>/delete', views.AlbumDelete.as_view(), name='album-delete'),
]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('music/', include('music.urls')),
]

music/models.py
from django.db import models
from django.urls import reverse
print(dir)
# Create your models here.
class Album(models.Model):
    artist = models.CharField(max_length = 20)
    album_title = models.CharField(max_length=20)
    genre = models.CharField(max_length=200)
    album_logo = models.CharField(max_length = 10000)


    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length = 20)
    song_title = models.CharField(max_length = 250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return  self.song_title

music/views.py
from django.views import generic
from .models import Album, Song
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from  django.urls import reverse_lazy

class IndexView(generic.ListView):
    template_name = 'music/index.html'
    # model = Album
    context_object_name = 'all_albums'


    def get_queryset(self):
        return Album.objects.all()


class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']


class AlbumUpdate(generic.UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo']

class AlbumDelete(generic.DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add{% endblock %}


{% block content %}
<div class="conatainer-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel pane-default">
                <div class="panel-body">

                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{%endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href="https://fots.googleapis.com/css?family=Satisfy" rel="stylesheet" type="text/css">

    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-f;uid">
<!--        <Header>-->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
        </div>

        <!-- tiltle-->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;
                        Albums
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;
                        Songs
                    </a>
                </li>
            </ul>

            <form class="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'music:album-add' %}">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;
                        Add Album
                    </a>
                </li>
                <li class="">
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;
                        Logout
                    </a>
                </li>
            </ul>

        </div>

    </div>
</nav>
{% block content %}
{% endblock %}


<script src="https://ajx.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.js"></script>
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
<title>{% block title %}Album Details {% endblock %}</title>
{% block content %}

<img src="{{ album.album_logo }}">

<h1>{{ album.album_title }}</h1>
<h3>{{ album.artist }}</h3>

{% if error_message %}
    <p><stron>{{ error_message }}</stron></p>
{% endif %}

<form action="#" method="post">
    {% csrf_token %}
    {% for song in album.song_set.all %}
        <input type="radio" id="song{{forloop.counter }}" name="song" value="{{ song.id }}"/>
        <label for="song{{ forloop.counter }}">
            {{ song.song_title }}

        </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>
{% endblock %}

music/templates/music/form-template.html
{% for field in form %}
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <span class="text-danger small">{{ field.errors }}</span>
    </div>
    <label class="control-label col-sm-2">{{field.label_tag }}</label>
    <div class="col-sm-10">{{field}}</div>
</div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
<title>{% block title %}Viberr {% endblock %}</title>
{% block content %}
{% if all_albums %}

    {% for album in all_albums }}
        <div class="col-sm-4 col-lg-2">
            <div class="thumbnail">
<!--                <a href="{% url 'music:detail' album.id %}">-->
<!--                    <img src="{{ album.album_logo.url }}" class="img-responsive">-->

<!--                </a>-->
                <div class="caption">
<!--                    <h2>{{album.title}}</h2>-->
<!--                    <h4>{{album.artist}}</h4>-->

<!--                    <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>-->


<!--                    <Delete>-->
                    <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                        {$ csrf_token %}
                        <input type="hidden" name="album_id" value="{{album.id}}"/>
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>


                </div>
            </div>
        </div>
{% else %}
    <div class="col-sm-12">
        <br>
        <a href="{% url 'music:album-add' %}">
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
            </button>
        </a>
    </div>
{% endif %}

{% endblock %}